### PR TITLE
Update vendored zstd c lib to 1.3.8

### PR DESCRIPTION
**Pull request by bai**
Update vendored zstd C library to version 1.3.8. Also, add Golang 1.12 to CI build matrix.

The reason I update CI linux dist from Ubuntu Trusty 14.04 to Ubuntu Xenial 16.04 is that 14.04 provides an old version of `ld` that [does not support relocation 42 on x86-64](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commitdiff;h=56ceb5b5405af23eddd12e12d8ba849010120324) (`R_X86_64_REX_GOTPCRELX`), causing:

```
/usr/bin/ld: /tmp/go-link-805134590/000043.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
```

### CODE REVIEW

**Comment by Viq111** [comment]
Hi @bai thanks for your contribution!

Yes it looks like the `ld` started popping up for all cgo code a couple of days ago: https://github.com/golang/go/issues/31293
This might get a patch on Go side but in the meantime, I'll do a separate PR to bump to xenial and unstuck the build.

**Comment by bai** [comment]
@Viq111 Many thanks. I'll rebase my branch once you ship Xenial.

**Comment by bai** [comment]
Rebased 👀

**Review by Viq111 — APPROVED** [review]
PR lgtm! Thanks a lot for your contribution.

This took a bit of time because I wanted to rerun the benchmarks.

Interestingly on a mac book pro, 1.3.8 is ~20% slower than `1.3.4`with the simple API:

```
goos: darwin
goarch: amd64
ᐅ benchstat old new
name                   old time/op    new time/op    delta
StreamCompression-4       194ms ±61%     177ms ± 3%     ~     (p=0.690 n=5+5)
StreamDecompression-4    37.3ms ±29%    29.6ms ± 4%     ~     (p=0.151 n=5+5)
Compression-4             140ms ±21%     179ms ± 5%  +27.69%  (p=0.008 n=5+5)
Decompression-4          20.5ms ± 5%    24.1ms ± 3%  +17.71%  (p=0.008 n=5+5)

name                   old speed      new speed      delta
StreamCompression-4    56.1MB/s ±43%  56.4MB/s ± 3%     ~     (p=0.690 n=5+5)
StreamDecompression-4   279MB/s ±35%   337MB/s ± 4%     ~     (p=0.151 n=5+5)
Compression-4          72.2MB/s ±19%  55.7MB/s ± 4%  -22.88%  (p=0.008 n=5+5)
Decompression-4         488MB/s ± 5%   414MB/s ± 3%  -15.08%  (p=0.008 n=5+5)
```

I ran it on a [`c5.9xlarge`](https://aws.amazon.com/ec2/instance-types/c5/) and there is no substantial differences:

```
goos: linux
goarch: amd64
name                    old time/op    new time/op    delta
StreamCompression-36       120ms ± 1%     125ms ± 2%  +3.77%  (p=0.008 n=5+5)
StreamDecompression-36    18.5ms ± 0%    19.6ms ± 0%  +6.07%  (p=0.008 n=5+5)
Compression-36             124ms ± 1%     123ms ± 4%    ~     (p=0.841 n=5+5)
Decompression-36          14.7ms ± 0%    15.3ms ± 1%  +4.01%  (p=0.008 n=5+5)

name                    old speed      new speed      delta
StreamCompression-36    82.8MB/s ± 1%  79.8MB/s ± 2%  -3.61%  (p=0.008 n=5+5)
StreamDecompression-36   539MB/s ± 0%   508MB/s ± 0%  -5.72%  (p=0.008 n=5+5)
Compression-36          80.7MB/s ± 1%  80.9MB/s ± 4%    ~     (p=0.841 n=5+5)
Decompression-36         679MB/s ± 0%   653MB/s ± 1%  -3.85%  (p=0.008 n=5+5)
```

Since I expect more people to run this for services on linux distributions, I'm 👍 to keep up to date with the zstd tree

**Comment by bai** [comment]
Huh, interesting. Numbers from my MacBook:

```
name                    old time/op    new time/op     delta
StreamCompression-12       103ms ± 0%      101ms ± 0%   ~     (p=1.000 n=1+1)
StreamDecompression-12    16.5ms ± 0%     16.5ms ± 0%   ~     (p=1.000 n=1+1)
Compression-12             101ms ± 0%      101ms ± 0%   ~     (p=1.000 n=1+1)
Decompression-12          14.1ms ± 0%     14.0ms ± 0%   ~     (p=1.000 n=1+1)

name                    old speed      new speed       delta
StreamCompression-12    99.0MB/s ± 0%  100.5MB/s ± 0%   ~     (p=1.000 n=1+1)
StreamDecompression-12   616MB/s ± 0%    617MB/s ± 0%   ~     (p=1.000 n=1+1)
Compression-12           101MB/s ± 0%    101MB/s ± 0%   ~     (p=1.000 n=1+1)
Decompression-12         724MB/s ± 0%    728MB/s ± 0%   ~     (p=1.000 n=1+1)
```

**Pull request merged**
