### PR TITLE
fix zstd_legacy.h path

### PR DESCRIPTION
**Pull request by candiduslynx**

### CODE REVIEW

**Review by Viq111 — COMMENTED** [review]
Thanks for the PR! This was indeed missed during the flattening of the directories

To be able to catch this in the future, do you mind adding it to the circleci test matrix ? Something like this should catch it: https://github.com/DataDog/zstd/commit/30b64e82d4f316a97cbcbf81f4ea31683da06efd

(feel free to cherry-pick this commit to your branch or do your own variation)

**Comment by candiduslynx** [comment]
> Thanks for the PR! This was indeed missed during the flattening of the directories
> 
> To be able to catch this in the future, do you mind adding it to the circleci test matrix ? Something like this should catch it: [30b64e8](https://github.com/DataDog/zstd/commit/30b64e82d4f316a97cbcbf81f4ea31683da06efd)
> 
> (feel free to cherry-pick this commit to your branch or do your own variation)

I've just added the code snipped you provided to the PR, feel free to recheck.

**Comment by Viq111** [comment]
Don't forget to add it to the run matrix as well 😉  (l.68) otherwise the new job will not be run

**Comment by candiduslynx** [comment]
> Don't forget to add it to the run matrix as well 😉 (l.68) otherwise the new job will not be run

done

**Review by Viq111 — APPROVED** [review]

**Pull request merged**
