### PR TITLE
zstd 1.3 -> zstd 1.3.3

### PR DESCRIPTION
**Pull request by ghatdev**

### CODE REVIEW

**Comment by Viq111** [comment]
Hi @ghatdev thanks for your PR!
Sorry I haven't been up to date on that repo but I just pushed the integration with Travis to run automatically the tests on PRs, would you mind pulling the latest changes from `1.x` branch to run those tests ?

**Comment by ghatdev** [comment]
oops I missed it. I just did!
there are some errors  with go test manually:

--- FAIL: TestZstdReaderLong (0.00s)
	zstd_stream_test.go:24: Compressed 130000 -> 33 bytes
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 8 [running]:
testing.tRunner.func1(0xc42009a3c0)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:711 +0x2d2
panic(0x41a0540, 0x4275be0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/ghatdev/go-zstd.Decompress.func1(0xc420062070, 0x63, 0x63, 0xc4200a4258, 0x21, 0x40, 0x0, 0xc420014340, 0xc420045cf8, 0x40b7405, ...)
	/Users/ghatdev/Work/Go/src/github.com/ghatdev/go-zstd/zstd.go:145 +0x184
github.com/ghatdev/go-zstd.Decompress(0x0, 0x63, 0x0, 0xc4200a4258, 0x21, 0x40, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/ghatdev/Work/Go/src/github.com/ghatdev/go-zstd/zstd.go:163 +0x129
github.com/ghatdev/go-zstd.testCompressionDecompression(0xc42009a3c0, 0x0, 0x0, 0x0, 0xc42016a000, 0x1fbd0, 0x267f3)
	/Users/ghatdev/Work/Go/src/github.com/ghatdev/go-zstd/zstd_stream_test.go:28 +0x37f
github.com/ghatdev/go-zstd.TestZstdReaderLong(0xc42009a3c0)
	/Users/ghatdev/Work/Go/src/github.com/ghatdev/go-zstd/zstd_stream_test.go:89 +0x10c
testing.tRunner(0xc42009a3c0, 0x41cd4d8)
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.2/libexec/src/testing/testing.go:789 +0x2de
exit status 2
FAIL	github.com/ghatdev/go-zstd	0.015s

**Comment by ghatdev** [comment]
I checked compress, decompress function only but they worked.

**Comment by ghatdev** [comment]
it seems to be some changes on ZSTD_decompress
zstd.go -> Decompress:written should be -13 but 1.3.3 headers return -70

**Comment by develar** [comment]
What's status of this PR?

**Comment by Viq111** [comment]
Hi, I haven't looked at updating it yet myself, I'll have more time the next upcoming week.
From what I see currently, is that there are actually some changes to make to the wrapper to be able to use `1.3.3`

**Comment by develar** [comment]
Thanks for status update. I use this zstd bindings for a tool creating tar.zstd files (https://github.com/develar/zstd-archiver) and it works great, but 1.3.3 brings multirthreads and long range matching.

**Comment by Viq111** [comment]
Hi @ghatdev , I was able to take some time this morning to debug your PR.

I added a PR to fix (== completly get rid of) the static mapping of error code between Go and C: https://github.com/DataDog/zstd/pull/29

I also pulled your branch and was able to make everything pass: https://github.com/DataDog/zstd/pull/28

Basically:
- ~Once https://github.com/DataDog/zstd/pull/29 is merged (currently in internal review),~ (merged) you can just merge `1.x` into your branch
- You need to cherry-pick https://github.com/DataDog/zstd/pull/28/commits/fc88a9da5a24391f630ba2eaf8ed6309fdc6e570 , zstd changed the compression window from 256kB to 128kB

Once this is done, I can merge that PR 👍

**Comment by ghatdev** [comment]
@Viq111  fc88a9d commit seems to be deleted from your test-1.3.3 branch in #28

**Comment by Viq111** [comment]
Ah github might be too aggressive when pruning loose objects (using `now` instead of 30 days).

I re-pushed to https://github.com/DataDog/zstd/commit/16974466973e945af0888fe3363061e0d15d1c4a

I think in your https://github.com/DataDog/zstd/pull/23/commits/5c047393a28d1dee64e7d66add7c518e7c971640 you missed `128 << 10` for `128 * 10`

(Build should be passing here: https://travis-ci.org/DataDog/zstd/builds/353765142)

**Comment by Viq111** [comment]
Great thanks a lot for your contribution! Looks good now and tests are passing.
Would you mind rebasing the history to have it a bit cleaner ?

**Comment by ghatdev** [comment]
@Viq111 I'm not good at using git :(.. Sorry about it.
Maybe I need some hints to do that.

**Comment by develar** [comment]
> rebasing the history to have it a bit cleaner ?

@Viq111 Hint — you can merge this PR using "Squash & merge" to have one rebased commit.

**Comment by ghatdev** [comment]
@develar Thx!
@Viq111 combined to 1 commit finally. Is this fine?

**Review by Viq111 — APPROVED** [review]
Perfect! Thanks a lot for the PR!

**Comment by Viq111** [comment]
@develar I usually don't like squashing because you loose git history (why a change was made).
Here, having a commit to update the C code and a separate commit for the CompressBound make it easy to understand what changed (and keep the commit message with an explanation)

**Pull request merged**
